databases:
  - name: imaginativestroll_DB
    databaseName: imaginativestroll_DB
    user: imaginativestroll
    region: singapore

services:
  - type: web
    name: imaginativestroll
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imaginativestroll_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

